### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by malled** [sepehr/xspfy#1]
I'm getting the error `INVALID_CLIENT: Invalid redirect URI` when I'm opening the URL to allow access.

I'm expecting to be redirected but that's not happening. What's wrong?

**Comment by alymenbr** [comment]
Me too. Can you take a look sepehr?

Thanks in advance!

**Comment by sepehr** [comment]
It's fixed in f362583. But there's a little glitch here; The spotify API does not accept the URI with the trailing slash. Github pages on the other hand; has issues loading the page without the trailing slash when query parameters are available.  

Here's an example of a failing redirect URI; it shows a github 404 error:

```
https://sepehr.github.io/laspotipy?code=AQBBBJQTkaFdsbcz8qs...
```

To workaround this for now, you need to append a trailing slash. Replace `laspotipy?code=` with `laspotipy/?code=` and you're good to go.  

I keep this open until I figure out a fix.

**Comment by alymenbr** [comment]
That was fast! Thanks for the fix and advice!

**Comment by kelvinlimtg** [comment]
Hi, so sorry, i've just started python and looking to play around with sonos and spotify. I've also extracted the xspf file from here successfully, https://github.com/stu247/spl but when I tried to install and run your script, I've got have success until below. Could you assist and perhaps point me to a potential solution? Thank you!

Traceback (most recent call last):
  File "xspfy.py", line 208, in <module>
    main()
  File "xspfy.py", line 161, in main
    if not pl.track:
AttributeError: 'bool' object has no attribute 'track'
