### ISSUE TITLE
Error importing xspf file to Spotify

### ISSUE THREAD

**Issue by kelvinlimtg** [sepehr/xspfy#2]
Hi, sorry, i've just started python and looking to play around with sonos and spotify. I've also extracted the xspf file from here successfully, https://github.com/stu247/spl but when I tried to install and run your script, I've got have success until below. Could you assist and perhaps point me to a potential solution? Thank you once again for the app!

Traceback (most recent call last):
File "xspfy.py", line 208, in 
main()
File "xspfy.py", line 161, in main
if not pl.track:
AttributeError: 'bool' object has no attribute 'track'

**Comment by h1rule** [comment]
same for me!

**Comment by sepehr** [comment]
I'll look into asap. Thanks for reporting.
